name: Build Polaris Obfuscator

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake git lld clang

      - name: Checkout Polaris Source
        uses: actions/checkout@v4
        with:
          repository: za233/Polaris-Obfuscator
          path: Polaris-Obfuscator

      - name: Build Polaris
        run: |
          cd Polaris-Obfuscator
          # 直接在源码根目录下创建build，然后用 ../llvm 指向llvm源代码
          mkdir build && cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=Off \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_TARGETS_TO_BUILD="X86" \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            ../llvm
          ninja -j $(nproc) clang

      - name: Package Polaris Artifact
        run: |
          # 回到工作区根目录
          mkdir -p Polaris-toolchain/bin
          # 二进制文件位于 Polaris-Obfuscator/build/bin/ 下
          cp Polaris-Obfuscator/build/bin/clang Polaris-toolchain/bin/
          cp Polaris-Obfuscator/build/bin/clang++ Polaris-toolchain/bin/
          cp Polaris-Obfuscator/build/bin/clang-cl Polaris-toolchain/bin/
          # 打包在当前目录，确保上传步骤能找到
          tar -czf polaris-toolchain.tar.gz Polaris-toolchain

      - name: Upload Polaris Artifact
        uses: actions/upload-artifact@v4
        with:
          name: polaris-toolchain
          path: polaris-toolchain.tar.gz
          if-no-files-found: error
