name: Build Polaris Obfuscator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja cmake git lld-18 clang-18

      - name: Checkout Polaris
        uses: actions/checkout@v4
        with:
          repository: za233/Polaris-Obfuscator
          ref: main
          path: Polaris-Obfuscator

      - name: Build Polaris
        run: |
          cd Polaris-Obfuscator/src
          mkdir build && cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=Off \
            -DLLVM_ENABLE_PROJECTS="clang;lld" \
            -DLLVM_TARGETS_TO_BUILD="X86" \
            -DLLVM_USE_LINKER=lld \
            -DCMAKE_C_COMPILER=clang-18 \
            -DCMAKE_CXX_COMPILER=clang++-18 \
            ../llvm
          ninja clang lld

      - name: Package Artifact
        run: |
          mkdir -p polaris-toolchain/bin
          cp Polaris-Obfuscator/src/build/bin/clang polaris-toolchain/bin/
          cp Polaris-Obfuscator/src/build/bin/clang++ polaris-toolchain/bin/
          cp Polaris-Obfuscator/src/build/bin/clang-cl polaris-toolchain/bin/
          cp Polaris-Obfuscator/src/build/bin/lld polaris-toolchain/bin/
          tar -czf polaris-toolchain.tar.gz polaris-toolchain

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: polaris-toolchain
          path: polaris-toolchain.tar.gz
          if-no-files-found: error
